/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminDepartmentsRouteImport } from './routes/superadmin.departments'
import { Route as SuperadminAuditRouteImport } from './routes/superadmin.audit'
import { Route as SuperadminAnalyticsRouteImport } from './routes/superadmin.analytics'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard.reports.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDepartmentsRoute = SuperadminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAuditRoute = SuperadminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAnalyticsRoute = SuperadminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperadminRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/submit': typeof SubmitRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/cases': typeof AdminCasesRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/departments': typeof SuperadminDepartmentsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submit': typeof SubmitRoute
  '/track': typeof TrackRoute
  '/admin/cases': typeof AdminCasesRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/departments': typeof SuperadminDepartmentsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/staff': typeof StaffIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/submit': typeof SubmitRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/track': typeof TrackRoute
  '/admin/cases': typeof AdminCasesRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/departments': typeof SuperadminDepartmentsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/staff'
    | '/submit'
    | '/superadmin'
    | '/track'
    | '/admin/cases'
    | '/dashboard/activity'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/superadmin/analytics'
    | '/superadmin/audit'
    | '/superadmin/departments'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/dashboard/'
    | '/staff/'
    | '/superadmin/'
    | '/dashboard/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/submit'
    | '/track'
    | '/admin/cases'
    | '/dashboard/activity'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/superadmin/analytics'
    | '/superadmin/audit'
    | '/superadmin/departments'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin'
    | '/dashboard'
    | '/staff'
    | '/superadmin'
    | '/dashboard/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/staff'
    | '/submit'
    | '/superadmin'
    | '/track'
    | '/admin/cases'
    | '/dashboard/activity'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/superadmin/analytics'
    | '/superadmin/audit'
    | '/superadmin/departments'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/dashboard/'
    | '/staff/'
    | '/superadmin/'
    | '/dashboard/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/departments': {
      id: '/superadmin/departments'
      path: '/departments'
      fullPath: '/superadmin/departments'
      preLoaderRoute: typeof SuperadminDepartmentsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/audit': {
      id: '/superadmin/audit'
      path: '/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof SuperadminAuditRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/analytics': {
      id: '/superadmin/analytics'
      path: '/analytics'
      fullPath: '/superadmin/analytics'
      preLoaderRoute: typeof SuperadminAnalyticsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardReportsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardReportsRouteChildren {
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
}

const DashboardReportsRouteChildren: DashboardReportsRouteChildren = {
  DashboardReportsIdRoute: DashboardReportsIdRoute,
}

const DashboardReportsRouteWithChildren =
  DashboardReportsRoute._addFileChildren(DashboardReportsRouteChildren)

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReportsRoute: typeof DashboardReportsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReportsRoute: DashboardReportsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StaffRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface SuperadminRouteChildren {
  SuperadminAnalyticsRoute: typeof SuperadminAnalyticsRoute
  SuperadminAuditRoute: typeof SuperadminAuditRoute
  SuperadminDepartmentsRoute: typeof SuperadminDepartmentsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAnalyticsRoute: SuperadminAnalyticsRoute,
  SuperadminAuditRoute: SuperadminAuditRoute,
  SuperadminDepartmentsRoute: SuperadminDepartmentsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
  SubmitRoute: SubmitRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
